[package]
name = "serial-direct-helloworld"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m-rt = "0.7"
panic-halt = "0.2.0"
defmt-rtt = "0.4"

[dependencies.microbit]
path = "../../microbit"
